services:
  web-server:
    build: .
    container_name: my-python-app
    stdin_open: true
    tty: true
    volumes:
      - .:/app  # <-- هذا هو الـ Volume الثاني: يربط مجلد المشروع الحالي بمجلد app داخل الحاوية
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: my-mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: my_first_db
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql  # هذا السطر هو "الخزنة" التي تحفظ بياناتك  

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: my-phpmyadmin
    links:
      - db
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: rootpassword